# Netflix Content Analysis
### Python Data Cleaning + Excel Dashboard

Objective:
Analyze Netflix content trends based on movies, TV shows, genres, countries, and ratings to uncover business insights.

In [13]:
import numpy as np 
import pandas as pd

In [14]:
df = pd.read_csv("Netflix.csv")
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [15]:
df.shape
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [16]:
df.drop_duplicates(inplace=True)

In [17]:
df["director"] = df["director"].fillna("Unknown")

In [18]:
df["cast"] = df["cast"].fillna("Unknown")

In [19]:
df["country"] = df["country"].fillna("Unknown")

In [20]:
df = df.dropna(subset = ['date_added','rating','duration'])

In [21]:
df.isna().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [22]:
df["date_added"] = pd.to_datetime(df["date_added"], errors="coerce")
df["year_added"] = df["date_added"].dt.year
df["year_added"]=df["year_added"].fillna(0).astype('int32')

C:\Users\Sarvesh\AppData\Local\Temp\ipykernel_32056\2456640821.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["date_added"] = pd.to_datetime(df["date_added"], errors="coerce")
C:\Users\Sarvesh\AppData\Local\Temp\ipykernel_32056\2456640821.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["year_added"] = df["date_added"].dt.year
C:\Users\Sarvesh\AppData\Local\Temp\ipykernel_32056\2456640821.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["year_added"]=df["year_added"].fillna(0).astype('int32')

In [23]:
df["genre"] = df["listed_in"].str.split(", ")
df = df.explode("genre")
df["genre"] = df["genre"].str.strip()

C:\Users\Sarvesh\AppData\Local\Temp\ipykernel_32056\1495308902.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["genre"] = df["listed_in"].str.split(", ")

In [24]:
df["country"] = df["country"].str.split(", ")
df = df.explode("country")
df["country"] = df["country"].str.strip()

In [35]:
df.groupby('type').size()

type
Movie      16868
TV Show     6857
dtype: int64

In [27]:
df.drop(columns="date_added",inplace=True)
df.drop(columns="listed_in",inplace=True)
df.drop(columns="description",inplace=True)

In [28]:
df.groupby('year_added').size()

year_added
0        208
2008       4
2009       3
2010       2
2011      29
2012       5
2013      27
2014      50
2015     181
2016    1081
2017    3175
2018    4487
2019    5362
2020    5150
2021    3961
dtype: int64

In [30]:
df.groupby(['year_added','type']).size().unstack(fill_value=0)

type        Movie  TV Show
year_added
0               0      208
2008            3        1
2009            3        0
2010            2        0
2011           29        0
2012            5        0
2013           10       17
2014           36       14
2015          135       46
2016          618      463
2017         2317      858
2018         3487     1000
2019         3887     1475
2020         3605     1545
2021         2731     1230

In [31]:
df['country'].value_counts().head(10)

country
United States     6764
India             2804
United Kingdom    1776
Unknown           1720
France             916
Canada             877
Japan              729
South Korea        632
Spain              591
Germany            511
Name: count, dtype: int64

In [32]:
df['genre'].value_counts().head(10)

genre
International Movies        3509
Dramas                      3198
Comedies                    1981
International TV Shows      1463
Action & Adventure          1182
Documentaries               1116
Independent Movies          1040
TV Dramas                    851
Children & Family Movies     845
Thrillers                    806
Name: count, dtype: int64

In [33]:
df['rating'].value_counts()

rating
TV-MA       8647
TV-14       5797
R           2499
TV-PG       2205
PG-13       1584
PG           904
TV-Y7        673
TV-Y         521
TV-G         500
NR           235
G            119
TV-Y7-FV      17
NC-17         13
UR            11
Name: count, dtype: int64

In [34]:
df.to_excel("netflix_cleaned.xlsx", index=False)

Key Insights:
- Netflix peaked in 2019
- Movies dominate the platform
- USA contributes highest content
- International Movies is top genre
- TV-MA is most common rating